### PR TITLE
Update normalize.css to v3.0.2

### PR DESCRIPTION
**Pull request by florianbouvot**
Hi Harry,

A PR to update inuitcss to lastest version of normalize.css.

Thanks, Florian.

### CODE REVIEW

**Comment by florianbouvot** [comment]
@csswizardry & @anselmh just a ping on this ;)

**Comment by anselmh** [comment]
Hey @florianbouvot sorry it has taken me so long to reply. I joined this group just a few days ago and while doing the npm stuff I updated normalize, too. I hadn’t really seen this pull request, did it my own. Sorry about that but thanks anyway for your contribution. Next time I’m happy to merge it.

**Comment by szarouski** [comment]
@anselmh can you please also update https://github.com/inuitcss/starter-kit/blob/master/bower.json to point to new version?

**Comment by anselmh** [comment]
@szarouski https://github.com/inuitcss/starter-kit/commit/47f5891cc5195bf543b1e1a0f67e5e24cde49208 done.

**Pull request closed without merging**
